baseURL = "https://YorigamiChitose.github.io/"
locale = "zh"
title = "YorigamiChitose"
theme = ["hugo-PaperMod", "hugo-notice"]
# theme = ["hugo-theme-stack", "hugo-notice"]
copyright = "© 2021-{{< year >}} [YorigamiChitose](https://YorigamiChitose.github.io/)"
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
defaultContentLanguage = "zh"

buildDrafts = false
buildFuture = false
buildExpired = false

summaryLength = 140

[pagination]
pagerSize = 15

[minify]
disableXML = true
minifyOutput = true

[permalinks]
post = "/:title/"

[params]
env = "productio"
defaultTheme = "auto"
math = true
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowToc = true
TocOpen = true
ShowWordCount = true
ShowReadingTime = true
ShowLastMod = true
hideAuthor = true
extendCodeBackground = false
enableInlineShortcodes = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
comments = true

[params.profileMode]
enabled = true
title = "Welcome!"
subtitle = "Here is YorigamiChitose's Blog"
imageUrl = "https://avatars.githubusercontent.com/u/161789380?v=4"

[[params.profileMode.buttons]]
name = "⏱️ 全部"
url = "/archives/"

[[params.profileMode.buttons]]
name = "📌 技术"
url = "/posts/tech/"

[[params.profileMode.buttons]]
name = "⛅ 日常"
url = "/posts/daily/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/YorigamiChitose"

[[params.socialIcons]]
name = "email"
url = "mailto:YorigamiChitose@outlook.com?subject=%5BFrom%20YorigamiChitose-Blog%5D%20Hello"

[params.cover]
linkFullImages = false

# [params.label]
# text = "YorigamiChitose"
# icon = "https://avatars.githubusercontent.com/u/161789380?v=4"
# iconHeight = 35

[params.assets]
favicon = "/img/favicon.ico"
favicon16x16 = "/img/favicon-16x16.png"
favicon32x32 = "/img/favicon-32x32.png"
apple_touch_icon = "/img/apple-touch-icon.png"
safari_pinned_tab = "/img/apple-touch-icon.png"
disableFingerprinting = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary"]

[params.giscus]
repo = "YorigamiChitose/YorigamiChitose.github.io"
repoId = "R_kgDOUCaJ2w"
category = "Announcements"
categoryId = "DIC_kwDOUCaJ284DEEQp"
mapping = "pathname"
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "zh-CN"
loading = "lazy"
crossorigin = "anonymous"

[[menu.main]]
identifier = "search"
name = "🔍 搜索"
url = "/search/"
weight = 0

[[menu.main]]
identifier = "home"
name = "🏠 主页"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "📚 文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "⏱️ 时间轴"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "🔖 标签"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "categories"
name = "🧩 分类"
url = "/categories/"
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
